require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CommentsController, type: :controller do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # adjust the attributes here as well.
  let!(:post1)  { FactoryBot.create(:post) }

  let(:valid_attributes) {
    user = create(:user)
    attributes_for(:comment).merge({post_id: post1.id, user_id: user.id})
  }

  let(:invalid_attributes) {
    attributes_for(:comment).merge({body: nil})
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Comment" do
        p valid_attributes
        expect {
          post :create, params: {comment: valid_attributes, post_id: post1.id}, session: valid_session
        }.to change(Comment, :count).by(1)
      end

      it "redirects to the post with latest comment" do
        post :create, params: {comment: valid_attributes, post_id: post1.id}, session: valid_session
        expect(response).to redirect_to(post_url(post1))
      end
    end

    context "with invalid params" do
      it "redirects to the post page" do
        post :create, params: {comment: invalid_attributes, post_id: post1.id}, session: valid_session
        expect(response).to redirect_to(post_url(post1))
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested comment" do
      comment = Comment.create! valid_attributes
      expect {
        delete :destroy, params: {id: comment.to_param, post_id: post1.id}, session: valid_session
      }.to change(Comment, :count).by(-1)
    end

    it "redirects to the comments list" do
      comment = Comment.create! valid_attributes
      delete :destroy, params: {id: comment.to_param, post_id: post1.id}, session: valid_session
      expect(response).to redirect_to(post_url(post1))
    end
  end

end
